prbl/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/about'
  get 'home/login'
  get 'home/send_contact'
  get 'home/guest'

  get 'finders/index'
  get 'finders/projects_status'
  get 'finders/projects_institution'


  resources :rubrics
  resources :teams
  resources :products
  resources :projects

  devise_for :teachers, path: 'teachers', controllers: {
      sessions: "teachers/sessions",
      registrations: "teachers/registrations"
    }

    root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

prbl/app/models/rubric.rb
class Rubric < ApplicationRecord
  belongs_to :project

  has_many :criteria, dependent: :destroy

  validates :name, presence: true
  validates :purpose_assessment, presence: true

  accepts_nested_attributes_for :criteria, reject_if: :all_blank, allow_destroy: true
end

prbl/app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :institution, presence: true
  validates :institutionCountry, presence: true
  validates :tipo, presence: true
  has_many :projects

  has_one :team

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

prbl/app/controllers/rubrics_controller.rb
class RubricsController < ApplicationController
  before_action :authenticate_teacher!
  before_action :set_rubric, only: [:show, :edit, :update, :destroy]

  # GET /rubrics
  # GET /rubrics.json
  def index
    @rubrics = Rubric.all
  end

  # GET /rubrics/1
  # GET /rubrics/1.json
  def show
  end

  # GET /rubrics/new
  def new
    @rubric = Rubric.new
    @criterium = @rubric.criteria.build
  end

  # GET /rubrics/1/edit
  def edit
  end

  # POST /rubrics
  # POST /rubrics.json
  def create
    @rubric = Rubric.new(rubric_params)

    respond_to do |format|
      if @rubric.save
        format.html { redirect_to @rubric, notice: 'Rubric was successfully created.' }
        format.json { render :show, status: :created, location: @rubric }
      else
        format.html { render :new }
        format.json { render json: @rubric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rubrics/1
  # PATCH/PUT /rubrics/1.json
  def update
    respond_to do |format|
      if @rubric.update(rubric_params)
        format.html { redirect_to @rubric, notice: 'Rubric was successfully updated.' }
        format.json { render :show, status: :ok, location: @rubric }
      else
        format.html { render :edit }
        format.json { render json: @rubric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rubrics/1
  # DELETE /rubrics/1.json
  def destroy
    @rubric.destroy
    respond_to do |format|
      format.html { redirect_to rubrics_url, notice: 'Rubric was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rubric
      @rubric = Rubric.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rubric_params
      params.require(:rubric).permit(:name, :purpose_assessment, :project_id,
        criteria_attributes: [:name, :bellow_standard, :approaching_standard, :meeting_standard])
    end
end

prbl/app/helpers/rubrics_helper.rb
module RubricsHelper
end

prbl/app/views/rubrics/_criterium_fields.html.erb
<div class="nested-fields">

  <h4>Criteria</h4>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :bellow_standard %>
    <%= f.text_field :bellow_standard %>

  </div>

  <div class="field">
    <%= f.label :approaching_standard %>
    <%= f.text_field :approaching_standard %>
  </div>


  <div class="field">
    <%= f.label :meeting_standard %>
    <%= f.text_field :meeting_standard %>
  </div>
<!-- COMENTÁRIO:
    link_to_remove_association é o helper que o cocoon nos fornece para deletar algum nested
  -->
  <%= link_to_remove_association "remove criterium", f %>

  <br><br><br>
</div>

prbl/app/views/rubrics/_form.html.erb
<%= form_with(model: rubric, local: true) do |form| %>
  <% if rubric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rubric.errors.count, "error") %> prohibited this rubric from being saved:</h2>

      <ul>
      <% rubric.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">

    <%= form.radio_button :purpose_assessment, 'Formative Assessment' %> Formative Assessment<br />
    <%= form.radio_button :purpose_assessment, 'Summative Assessment' %> Summative Assessment<br />
    <%= form.radio_button :purpose_assessment, 'Other' %> Other<br />

    <%= form.label :purpose_assessment %>
    <%= form.text_field :purpose_assessment %>
  </div>

  <div id="criteria">

    <%= form.fields_for :criteria do |criteria_fields| %>

      <%= render partial: "criterium_fields", locals: {f: criteria_fields} %>
    <% end %>

    <div class="links">
          <!-- COMENTÁRIO: O link_to_add_association é um helper provido pela gem -->
          <%= link_to_add_association 'add Criteria', form, :criteria %>
          <br><br>
        </div>

  </div>

  <div class="field">
    <%= hidden_field_tag 'rubric[project_id]', current_teacher.project_ids %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

prbl/app/views/rubrics/edit.html.erb
<h1>Editing Rubric</h1>

<%= render 'form', rubric: @rubric %>

<%= link_to 'Show', @rubric %> |
<%= link_to 'Back', rubrics_path %>

prbl/app/views/rubrics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rubrics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Purpose assessment</th>
      <th>Project</th>
      <th>Driven Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rubrics.each do |rubric| %>
      <tr>
        <td><%= rubric.name %></td>
        <td><%= rubric.purpose_assessment %></td>
        <td><%= rubric.project.title %></td>
        <td><%= rubric.project.driven_question %></td>
        
        <td><%= link_to 'Show', rubric %></td>
        <td><%= link_to 'Edit', edit_rubric_path(rubric) %></td>
        <td><%= link_to 'Destroy', rubric, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rubric', new_rubric_path %>

prbl/app/views/rubrics/new.html.erb
<h1>New Rubric</h1>

<%= render 'form', rubric: @rubric %>

<%= link_to 'Back', rubrics_path %>

prbl/app/views/rubrics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rubric.name %>
</p>

<p>
  <strong>Purpose assessment:</strong>
  <%= @rubric.purpose_assessment %>
</p>

<p>
  <strong>Project:</strong>
  <%= @rubric.project.title %>
</p>

<p>
  <strong>Project Driven Question:</strong>
  <%= @rubric.project.driven_question %>
</p>

<%= link_to 'Edit', edit_rubric_path(@rubric) %> |
<%= link_to 'Back', rubrics_path %>