prbl/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/about'
  get 'home/login'
  get 'home/send_contact'
  get 'home/guest'

  get 'finders/index'
  get 'finders/projects_status'
  get 'finders/projects_institution'


  resources :rubrics
  resources :teams
  resources :products
  resources :projects

  devise_for :teachers, path: 'teachers', controllers: {
      sessions: "teachers/sessions",
      registrations: "teachers/registrations"
    }

    root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

prbl/app/models/project.rb
class Project < ApplicationRecord
  belongs_to :teacher

  has_many :products, dependent: :destroy

  has_many :teams, dependent: :destroy

  has_many :rubrics, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :duration, presence: true
  validates :course, presence: true
  validates :course_level, presence: true
  validates :other_subject_area, presence: true
  validates :entry_event, presence: true
  validates :compentences, presence: true
  validates :onsite_people_facilities, presence: true
  validates :equipments, presence: true
  validates :materials, presence: true
  validates :community_resources, presence: true
  validates :reflection_methods, presence: true
  validates :institution, presence: true

  accepts_nested_attributes_for :products, reject_if: :all_blank, allow_destroy: true
end

prbl/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_teacher!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.where(teacher_id: current_teacher.id)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @product = @project.products.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @teacher = Teacher.where(teacher_id: current_teacher.id)


    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :duration, :status, :course, :course_level, :other_subject_area, :driven_question, :entry_event, :compentences, :product_public, :onsite_people_facilities, :equipments, :materials, :community_resources,
        :reflection_methods, :notes, :institution, :teacher_id, products_attributes: [:name, :team_or_individual, :due_date])
    end
end

prbl/app/helpers/projects_helper.rb
module ProjectsHelper
end

prbl/app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, options_for_select([["Will Still Start",'Will Still Start'], ["In Progress", 'In Progress'], ["Completed", 'Completed']]) %>
  </div>


  <div class="field">
    <%= form.label :course %>
    <%= form.text_field :course %>
  </div>

  <div class="field">
    <%= form.label :course_level %>
    <%= form.text_field :course_level %>
  </div>

  <div class="field">
    <%= form.label :other_subject_area %>
    <%= form.text_field :other_subject_area %>
  </div>

  <div class="field">
    <%= form.label :driven_question %>
    <%= form.text_field :driven_question %>
  </div>

  <div class="field">
    <%= form.label :entry_event %>
    <%= form.text_field :entry_event %>
  </div>

  <div class="field">
    <%= form.label :product_public %>
    <%= form.check_box :product_public %>
  </div>

  <div class="field">
    <%= form.label :onsite_people_facilities %>
    <%= form.text_field :onsite_people_facilities %>
  </div>

  <div class="field">
    <%= form.label :equipments %>
    <%= form.text_field :equipments %>
  </div>

  <div class="field">
    <%= form.label :materials %>
    <%= form.text_field :materials %>
  </div>

  <div class="field">
    <%= form.label :community_resources %>
    <%= form.text_field :community_resources %>
  </div>

  <div class="field">
    <h2>21st Century Competences </h2>
  <%= form.label :compentences %>
    <%= form.select :compentences, options_for_select([["Critical Thinking",'Critical Thinking'],
      ["Communication", 'Communication'], ["Creativity", 'Creativity'], ["Collaboration",'Collaboration'],
      ["Character",'Character'], ["Citizenship",'Citizenship']]) %>
  </div>

  <div class="field">
    <!-- <%= form.label :reflection_methods %>
    <%= form.text_field :reflection_methods %> -->
      <h2>Reflection Methods </h2>
     <%= form.radio_button :reflection_methods, 'Journal/Learning Log' %> Journal/Learning Log<br />
     <%= form.radio_button :reflection_methods, 'Focus Group' %> Focus Group<br />
     <%= form.radio_button :reflection_methods, 'Whole Class Discussion' %> Whole Class Discussion<br />
     <%= form.radio_button :reflection_methods, 'Fishbown Discussion' %> Fishbown Discussion<br />
     <%= form.radio_button :reflection_methods, 'Survey' %> Survey<br />
     <%= form.radio_button :reflection_methods, 'Journal/Learning Cafe' %> Journal/Learning Cafe<br />

  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_field :notes %>
  </div>

  <div class="field">
    <%= hidden_field_tag 'project[teacher_id]', current_teacher.id  %>
  </div>

  <div class="field">
    <%= hidden_field_tag 'project[institution]', current_teacher.institution  %>
  </div>

  <div id="products">
    <%= form.fields_for :products do |products_fields| %>

      <%= render partial: "product_fields", locals: {f: products_fields} %>
    <% end %>

    <div class="links">
          <!-- COMENTÁRIO: O link_to_add_association é um helper provido pela gem -->
          <%= link_to_add_association 'add product', form, :products %>
          <br><br>
        </div>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

prbl/app/views/projects/_product_fields.html.erb
<div class="nested-fields">

  <h4>Products</h4>
  
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :team_or_individual %>
    <%= f.select :team_or_individual, options_for_select([["Team",'Team'], ["Individual", 'Individual']]) %>

    <!-- <%= f.text_field :team_or_individual %> -->

  </div>

  <div class="field">
    <%= f.label :due_date %>
    <%= f.date_select :due_date, :order => [:day, :month, :year] %>
  </div>
  <!-- COMENTÁRIO:
    link_to_remove_association é o helper que o cocoon nos fornece para deletar algum nested
  -->
  <%= link_to_remove_association "remove product", f %>

  <br><br><br>
</div>

prbl/app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

prbl/app/views/projects/index.html.erb
<div class="">
  <h2 class="display-2"> <%= current_teacher.name %> Projects </h2>
</div>

<br><br><br>

<div class="panel">
  <table class="table table-sm table table-hover table table-bordered">
    <thead align="center" class="thead-light">
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Duration</th>
        <th scope="col">Status</th>
        <th scope="col">Course</th>
        <th scope="col">Course level</th>
        <th scope="col">Other subject area</th>
        <th scope="col">Teacher</th>
        <th scope="col">Project Details</th>
        <th scope="col">Modify Project</th>
        <th scope="col">Exclude Project</th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td align="center"><%= project.title %></td>
          <td align="center"><%= project.duration %></td>
          <td align="center"><%= project.status %></td>
          <td align="center"><%= project.course %></td>
          <td align="center"><%= project.course_level %></td>
          <td align="center"><%= project.other_subject_area %></td>
          <td align="center"><%= project.teacher.name %></td>
          <td align="center"><%= link_to 'Details', project %></td>
          <td align="center"><%= link_to 'Modify', edit_project_path(project) %></td>
          <td align="center"><%= link_to 'Exclude', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<p><a class="btn btn-primary" href="<%= new_project_path %>" role="button">Create a new Project</a></p>

prbl/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

prbl/app/views/projects/show.html.erb
<div class="jumbotron" align="center">
  <h1><strong>Title:</strong>
  <%= @project.title %></h1>

  <ul class="list-group">
    <li class="list-group-item"> <strong>Duration: </strong><%= @project.duration %></li>
    <li class="list-group-item">  <strong>Status: </strong> <%= @project.status %></li>
    <li class="list-group-item"><strong>Course: </strong> <%= @project.course %></li>
    <li class="list-group-item"><strong>Course level: </strong> <%= @project.course_level %></li>
    <li class="list-group-item"><strong>Other subject area:</strong>
    <%= @project.other_subject_area %></li>
    <li class="list-group-item"><strong>Driven question:</strong>
    <%= @project.driven_question %>
</li>
    <li class="list-group-item"><strong>Entry event:</strong>
    <%= @project.entry_event %>
</li>
    <li class="list-group-item"><strong>Compentences:</strong>
    <%= @project.compentences %>
</li>
    <li class="list-group-item"><strong>Product public:</strong>
    <%= @project.product_public %></li>
    <li class="list-group-item">  <strong>Onsite people facilities:</strong>
      <%= @project.onsite_people_facilities %>
</li>
    <li class="list-group-item">  <strong>Equipments:</strong>
      <%= @project.equipments %>
</li>
    <li class="list-group-item"><strong>Materials:</strong>
    <%= @project.materials %></li>
    <li class="list-group-item">  <strong>Community resources:</strong>
      <%= @project.community_resources %></li>
    <li class="list-group-item">  <strong>Reflection methods:</strong>
      <%= @project.reflection_methods %></li>
    <li class="list-group-item">  <strong>Notes:</strong>
      <%= @project.notes %></li>
    <li class="list-group-item">  <strong>Teacher:</strong>
      <%= @project.teacher.name %></li>

    <br>
    <% if teacher_signed_in? %>
    <p><a class="btn btn-primary btn-lg" href="<%= teams_path(@project) %>" role="button">Manage Teams</a></p>
    <p><a class="btn btn-primary btn-lg" href="<%= edit_product_path(@project) %>" role="button">Student Learning Guide</a></p>
    <p><a class="btn btn-primary btn-lg" href="<%= rubrics_path(@project) %>" role="button">Rubrics</a></p>

    <% end %>
  </ul>
  </div>
</div>