prbl/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/about'
  get 'home/login'
  get 'home/send_contact'
  get 'home/guest'

  get 'finders/index'
  get 'finders/projects_status'
  get 'finders/projects_institution'


  resources :rubrics
  resources :teams
  resources :products
  resources :projects

  devise_for :teachers, path: 'teachers', controllers: {
      sessions: "teachers/sessions",
      registrations: "teachers/registrations"
    }

    root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

prbl/app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-dark   bg-info">
  <a class="navbar-brand" href="<%= root_path %>">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <% if teacher_signed_in? %>
          <a class="nav-item nav-link" href="<%= projects_path %>">My Projects</a>
          <% else %>
          <a class="nav-item nav-link" href="<%= finders_index_path %>">Search Projects <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="<%= home_guest_path %>">Contact Us <span class="sr-only">(current)</span></a>

      <% end %>
      <a class="nav-item nav-link" href="<%= home_about_path %>">About Project Based Learning</a>
    </div>
  </div>

  <p class="navbar-text pull-right">

    <div class="navbar-nav">
      <% if teacher_signed_in? %>
        <a class="nav-item nav-link" href="">Logged as <%= current_teacher.name %></a>
      <%= link_to 'View profile', edit_teacher_registration_path, :class => 'nav-link' %>
      <%= link_to "Close Session", destroy_teacher_session_path, method: :delete, :class => 'nav-link'  %>
          <% else %>
          <%= link_to "Login", new_teacher_session_path, :class => 'nav-link' %>
          <%= link_to "Sign Up", new_teacher_registration_path, :class => 'nav-link' %>
      <% end %>
    </div>

</nav>

prbl/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrBL Tool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/menu" %>
    <%= yield %>
  </body>
</html>