prbl/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/about'
  get 'home/login'
  get 'home/send_contact'
  get 'home/guest'

  get 'finders/index'
  get 'finders/projects_status'
  get 'finders/projects_institution'


  resources :rubrics
  resources :teams
  resources :products
  resources :projects

  devise_for :teachers, path: 'teachers', controllers: {
      sessions: "teachers/sessions",
      registrations: "teachers/registrations"
    }

    root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

prbl/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :project

  validates :name, presence: true
  validates :team_or_individual, presence: true
  validates :due_date, presence: true

end

prbl/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_teacher! 
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit

    # @product = Product.where(project_id: params[:id])

  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :team_or_individual, :due_date, :learning_outcomes, :checkpoints, :learning_strategies, :project_id)
    end
end

prbl/app/helpers/products_helper.rb
module ProductsHelper
end

prbl/app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <strong>Product Name:</strong>
    <%= @product.name %>
  </p>

  <p>
    <strong>Team or individual:</strong>
    <%= @product.team_or_individual %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= @product.due_date %>
  </p>

  <div class="field">
    <%= form.label :learning_outcomes %>
    <%= form.text_field :learning_outcomes %>
  </div>

  <div class="field">
    <%= form.label :checkpoints %>
    <%= form.text_field :checkpoints %>
  </div>

  <div class="field">
    <%= form.label :learning_strategies %>
    <%= form.text_field :learning_strategies %>
  </div>

  <div class="field">
    <%= hidden_field_tag 'product[project_id]', @product.project.id  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

prbl/app/views/products/edit.html.erb
<h1>Learning Guide</h1>

<%= render 'form', product: @product %>

<br>
<p><a class="btn btn-primary" href="<%= products_path %>" role="button">Back to Projects</a></p>

prbl/app/views/products/index.html.erb
<div class="">
  <h2 class="display-2"> My Products </h2>
</div>

<br><br><br>

<div class="panel">
  <table class="table table-sm table table-hover table table-bordered">
    <thead align="center" class="thead-light">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Team or individual</th>
        <th scope="col">Due date</th>
        <th scope="col">Learning outcomes</th>
        <th scope="col">Checkpoints</th>
        <th scope="col">Learning strategies</th>
        <th scope="col">Project</th>
        <th scope="col">Product Details</th>
        <th scope="col">Modify Product</th>
        <th scope="col">Exclude Product</th>
      </tr>
    </thead>

      <% @products.each do |product| %>
        <tr>
          <td align="center"><%= product.name %></td>
          <td align="center"><%= product.team_or_individual %></td>
          <td align="center"><%= product.due_date %></td>
          <td align="center"><%= product.learning_outcomes %></td>
          <td align="center"><%= product.checkpoints %></td>
          <td align="center"><%= product.learning_strategies %></td>
          <td align="center"><%= product.project.title %></td>
          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

prbl/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

prbl/app/views/products/show.html.erb
<div class="jumbotron" align="center">
  <h1><strong>Project:</strong>
  <%= @product.project.title %></h1>
<br>
  <h2><strong>Driven Question:</strong>
  <%= @product.project.driven_question %></h2>

<br>

  <ul class="list-group">

    <li class="list-group-item"><p>
      <strong>Product: </strong>
      <%= @product.name %>
    </p></li>
    <li class="list-group-item"><strong>Team or individual:</strong>
      <%= @product.team_or_individual %></li>
    <li class="list-group-item">  <strong>Due date:</strong>
      <%= @product.due_date %></li>
    <li class="list-group-item"><strong><strong>Learning outcomes:</strong>
    <%= @product.learning_outcomes %></li>
    <li class="list-group-item"><p>
      <strong>Checkpoints:</strong>
      <%= @product.checkpoints %>
    </p></li>
    <br>
    <p><a class="btn btn-primary" href="<%= projects_path %>" role="button">Back</a></p>

  </ul>
  </div>
</div>